version: "3"
services:

  mongodb:
    image: bitnami/mongodb:latest
    environment:
      - MONGODB_ROOT_PASSWORD=admin
      # Activate this if connecting from localhost
      #      - MONGODB_ADVERTISED_HOSTNAME=localhost
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_KEY=replicaset
    ports:
      - "27017:27017"
    volumes:
      - ./test/init-mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  rabbitmq:
    image: rabbitmq:3.8.2-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
