version: "3.5"

services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - $FDKHARVESTADM_SERVER_PORT:$FDKHARVESTADM_SERVER_PORT
      - $FDKHARVESTADM_SERVER_DEBUG_PORT:$FDKHARVESTADM_SERVER_DEBUG_PORT
    links:
      - mongo
    command: npm start

  mongo:
    container_name: mongo
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$FDKHARVESTADM_MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$FDKHARVESTADM_MONGO_PASSWORD
    ports:
      - 27017:27017
