version: "3"

services:
  fdk-harvest-admin:
    build: ../fdk-harvest-admin
    environment:
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=admin
    ports:
      - "8134:8080"
    depends_on:
      - mongodb