---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment-fdk-harvest-admin.yaml
  - service-fdk-harvest-admin.yaml
images:
  - name: fdk-harvest-admin
    newName: ghcr.io/informasjonsforvaltning/fdk-harvest-admin
    newTag: $(GIT_COMMIT_SHA)
